"use client";
import {useEffect,useState} from "react";
const nav=[["Overview","/dashboard"],["Live Drive","/telemetry"],["My Miles","/dashboard#miles"],["Trips","/dashboard#trips"],["Fleet","/fleet"],["Events","/events"]];
export default function Dashboard(){
 const [data,setData]=useState(null),[message,setMessage]=useState("Welcome back, driver. Your BC TRUCK WORKS AI copilot is ready.");
 useEffect(()=>{fetch("/api/driver").then(r=>r.ok?r.json():null).then(setData).catch(()=>{});const id=setInterval(()=>fetch("/api/driver").then(r=>r.ok?r.json():null).then(setData).catch(()=>{}),5000);return()=>clearInterval(id)},[]);
 const d=data?.driver,t=data?.latestTelemetry;
 const speak=()=>{if(typeof window!=="undefined"&&"speechSynthesis"in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(message));}};
 return <main className="platform dashboard-shell">
  <aside className="sidebar"><a className="side-brand" href="/"><img src="/bc-truck-works-logo.svg" alt=""/> <span>BC TRUCK<br/>WORKS</span></a><div className="side-status"><i/> LIVE PLATFORM</div><nav>{nav.map(([label,href],i)=><a className={i===0?"active":""} href={href} key={label}><span>{["⌂","◉","↗","▤","🚛","★"][i]}</span>{label}</a>)}</nav><div className="side-ai"><small>BC AI COPILOT</small><p>“Keep your eyes on the road. I’ll keep track of the miles.”</p><button onClick={speak}>🔊 Speak to me</button></div><a className="side-back" href="/">← Main Website</a></aside>
  <section className="dashboard main-dashboard">
   <div className="dash-top"><div><span className="eyebrow">DRIVER HUB • {d?"LIVE":"READY"}</span><h1>{d?`Welcome back, ${d.display_name}.`:"Your road starts here."}</h1><p className="muted">{d?"Real driving data is flowing into your Driver Hub.":"Login with Discord to connect your driver account."}</p></div>{!d&&<a className="primary" href="/api/auth/discord">Login with Discord →</a>}</div>
   {d&&<><div className="live-banner"><i/> LIVE GAME DATA <span>{t?.game||d.game||"WAITING"} • {t?Number(t.speed).toFixed(0):"0"} km/h</span></div>
   <div className="metric-grid" id="miles"><div className="metric"><small>TOTAL MILES</small><strong>{Number(d.total_miles||0).toLocaleString(undefined,{maximumFractionDigits:1})}</strong><span>Tracked from game telemetry</span></div><div className="metric" id="trips"><small>TRIPS</small><strong>{d.trips||0}</strong><span>ATS + ETS2</span></div><div className="metric"><small>DELIVERIES</small><strong>{d.deliveries||0}</strong><span>Recorded deliveries</span></div><div className="metric"><small>RANK</small><strong>{d.rank?`#${d.rank}`:"—"}</strong><span>Community leaderboard</span></div></div>
   <div className="hero-panel"><div className="big-card"><span className="eyebrow">LIVE DRIVE</span><h2>{t?.game||"Waiting for game"}</h2><div className="live-readout"><strong>{t?Number(t.speed).toFixed(0):"0"}</strong><span>KM/H</span></div><div className="row"><strong>Odometer</strong><span>{t?.odometer!=null?Number(t.odometer).toFixed(1):"Waiting"}</span></div><div className="row"><strong>Fuel</strong><span>{t?.fuel!=null?Number(t.fuel).toFixed(1):"Waiting"}</span></div><div className="row"><strong>Telemetry</strong><span>{t?"● CONNECTED":"○ WAITING"}</span></div></div><div className="big-card"><span className="eyebrow">AI COPILOT</span><h2>Road Assistant</h2><p className="muted">{message}</p><button className="primary ai-button" onClick={speak}>🔊 Let BC AI speak</button><button className="secondary ai-button" onClick={()=>setMessage("Telemetry is connected. Keep driving safely. I’m tracking your miles automatically.")}>Generate driving update</button></div></div></>}
   {!d&&<div className="panel"><h2>Connect your real game</h2><p className="muted">Once you sign in and run the BC TRUCK WORKS connector with ATS or ETS2, this dashboard will populate with your real mileage, speed, fuel, odometer and trip data.</p></div>}
  </section>
 </main>
}